version: 1.0.{build}
image: Visual Studio 2019
configuration: Release
platform: x64

build: off

deploy_script:
  - ps: |
      # Get Latest Pulumi Version
      $version = (Invoke-WebRequest -UseBasicParsing https://www.pulumi.com/latest-version).Content.Trim()
      $url = "https://get.pulumi.com/releases/sdk/pulumi-v${version}-windows-x64.zip"
      $output = "pulumi-v${version}-windows-x64.zip"

      Set-Location -Path .\pulumi\
      (Get-Content '.\pulumi.nuspec' -Raw).Replace("<version>X.X.X</version>", "<version>${version}</version>") | Out-File '.\pulumi.nuspec'
      
      Set-Location -Path .\tools
      Invoke-WebRequest -Uri $url -OutFile $output
      (Get-Content '.\chocolateyinstall.ps1' -Raw).Replace("X.X.X", "${version}") | Out-File '.\chocolateyinstall.ps1'
      $checksum = Get-FileHash -Path $output
      $hash = $checksum.Hash

      Set-Location -Path ..\legal
      (Get-Content '.\VERIFICATION.txt') | Foreach-Object {
          $_ -replace 'XXXXXX', "${hash}" `
            -replace 'X.X.X', "${version}"
          } | Set-Content '.\VERIFICATION.txt'
      $licenseFileUrl = "https://raw.githubusercontent.com/pulumi/pulumi/v${version}/LICENSE"
      $licenseFileOutput = "LICENSE.txt"
      Invoke-WebRequest -Uri $licenseFileUrl -OutFile $licenseFileOutput
      Get-Content -Path .\VERIFICATION.txt

      Set-Location -Path ..\
      Choco Pack 
      
      choco push -k $env:CHOCO_API_KEY -s https://push.chocolatey.org/